openapi: "3.0.3"
info:
  title: "Friends App API"
  version: "0.1.0"
  description: |
    HTTP API for the `friends` app - A decentralized friend management system.
    
    The friends app allows users to:
    - Send friend invitations to other users
    - Accept or ignore incoming invitations
    - Maintain a list of friends
    - Search for people in the directory
    
    **Friend Invitation Flow:**
    1. User A sends invitation to User B via `/create`
    2. User B receives invitation and can `/accept` or `/ignore`
    3. Upon acceptance, both users have each other as friends
    
    **Smart Invitation Handling:**
    - If User B already sent an invitation to User A, and User A tries to invite User B, they automatically become friends
    - This prevents duplicate invitations and streamlines the friend connection process

paths:
  "/friends/create":
    post:
      summary: Create or invite a friend
      description: |
        Adds a person as a friend or sends them a friend invitation.
        
        **Behavior:**
        - If they already invited you: Automatically accepts their invitation and adds them as a friend
        - If they haven't invited you: Sends them an invitation (they must accept to become friends)
        - If the ID is not a valid entity: Skips message sending but returns success
      security:
        - cookieAuth: []
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id, name]
              properties:
                id:
                  type: string
                  description: "Entity ID of the person to add or invite"
                  example: "ent_abc123xyz"
                name:
                  type: string
                  description: "Display name for the friend"
                  example: "Alice Johnson"
      responses:
        "200":
          description: Friend created or invitation sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyData'
        "400":
          description: Missing friend ID or name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  "/friends/accept":
    post:
      summary: Accept a friend invitation
      description: |
        Accepts an incoming friend invitation from another user.
        
        **Actions performed:**
        - Adds the person to your friends list
        - Sends acceptance notification to the person who invited you
        - Removes the invitation from your invites list
      security:
        - cookieAuth: []
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id]
              properties:
                id:
                  type: string
                  description: "Entity ID of the friend who invited you"
                  example: "ent_def456uvw"
      responses:
        "200":
          description: Invitation accepted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyData'
        "400":
          description: Missing friend ID or invitation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  "/friends/delete":
    post:
      summary: Remove a friend or cancel an invitation
      description: |
        Removes a friend from your friends list or cancels an outgoing/incoming invitation.
        
        **Behavior:**
        - If they are a friend: Removes them from your friends list
        - If you sent them an invitation: Cancels the outgoing invitation
        - If they sent you an invitation: Removes the incoming invitation
      security:
        - cookieAuth: []
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id]
              properties:
                id:
                  type: string
                  description: "Entity ID of the friend or invitation to remove"
                  example: "ent_ghi789rst"
      responses:
        "200":
          description: Friend or invitation removed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyData'
        "400":
          description: Missing friend ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  "/friends/ignore":
    post:
      summary: Ignore (decline) a friend's invitation
      description: |
        Declines an incoming friend invitation without adding the person as a friend.
        
        **Note:** This only removes incoming invitations (direction='from'). 
        To cancel your own outgoing invitations, use `/delete` instead.
      security:
        - cookieAuth: []
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id]
              properties:
                id:
                  type: string
                  description: "Entity ID of the person whose invitation to ignore"
                  example: "ent_jkl012mno"
      responses:
        "200":
          description: Invitation ignored successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyData'
        "400":
          description: Missing friend ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  "/friends/list":
    post:
      summary: List friends and incoming invitations
      description: |
        Returns the complete list of friends and pending incoming invitations.
        
        **Returns:**
        - `friends`: All confirmed friends (sorted by name)
        - `invites`: Only incoming invitations that need your response (sorted by most recent)
        
        **Note:** Outgoing invitations (that you sent) are not included in this list.
      security:
        - cookieAuth: []
        - bearerAuth: []
      responses:
        "200":
          description: Friends and invitations list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponse'
        "401":
          description: Not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  "/friends/search":
    post:
      summary: Search directory for people to add as friends
      description: |
        Searches the directory for people matching the search term.
        
        **Features:**
        - Searches for entities with class "person"
        - Returns deduplicated results (each person appears only once)
        - Includes relationship status for each result to help UI show appropriate actions
        
        **Relationship Status:**
        - `friend`: Already friends with this person
        - `invited`: You have sent an invitation to this person (waiting for their response)
        - `pending`: This person has sent you an invitation (you can accept)
        - `self`: This is your own profile
        - `none`: No existing relationship (can send new invitation)
      security:
        - cookieAuth: []
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [search]
              properties:
                search:
                  type: string
                  description: "Search term to find people"
                  example: "john"
      responses:
        "200":
          description: Search results with deduplicated people and relationship status
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/Person'
        "401":
          description: Not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: login
      description: "Login cookie set after successful authentication"
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT token or legacy login token in Authorization header"
    headerAuth:
      type: apiKey
      in: header
      name: X-Login
      description: "Login token in X-Login header"

  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          description: "HTTP status code"
          example: 400
        error:
          type: string
          description: "Error message"
          example: "Missing friend ID"
        data:
          type: object
          description: "Empty data object"

    EmptyData:
      type: object
      properties:
        data:
          type: object
          description: "Empty successful response data"

    Friend:
      type: object
      properties:
        identity:
          type: string
          description: "Your identity ID (the owner of the friends list)"
          example: "ent_user123"
        id:
          type: string
          description: "Friend's entity ID"
          example: "ent_friend456"
        name:
          type: string
          description: "Friend's display name"
          example: "Alice Johnson"
        class:
          type: string
          description: "Entity class (always 'person' for friends)"
          example: "person"

    Invite:
      type: object
      properties:
        identity:
          type: string
          description: "Your identity ID (the recipient of the invitation)"
          example: "ent_user123"
        id:
          type: string
          description: "Entity ID of the person who sent the invitation"
          example: "ent_inviter789"
        direction:
          type: string
          enum: [from, to]
          description: |
            Direction of the invitation:
            - `from`: Incoming invitation (they invited you)
            - `to`: Outgoing invitation (you invited them)
          example: "from"
        name:
          type: string
          description: "Display name of the person who sent the invitation"
          example: "Bob Smith"
        updated:
          type: integer
          description: "Unix timestamp of when the invitation was last updated"
          example: 1701388800

    ListResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            friends:
              type: array
              description: "List of confirmed friends, sorted by name"
              items:
                $ref: '#/components/schemas/Friend'
            invites:
              type: array
              description: "List of incoming invitations only (direction='from'), sorted by most recent"
              items:
                $ref: '#/components/schemas/Invite'

    Person:
      type: object
      description: "A person entity from directory search results"
      properties:
        id:
          type: string
          description: "Entity ID of the person"
          example: "ent_person789"
        name:
          type: string
          description: "Display name of the person"
          example: "Charlie Davis"
        fingerprint:
          type: string
          description: "Human-readable identifier (if available)"
          example: "charlie-davis"
        class:
          type: string
          description: "Entity class"
          example: "person"
        relationshipStatus:
          type: string
          enum: [friend, invited, pending, self, none]
          description: |
            Current relationship status with this person:
            - `friend`: Already friends
            - `invited`: You sent them an invitation (outgoing)
            - `pending`: They sent you an invitation (incoming)
            - `self`: This is your own profile
            - `none`: No existing relationship
          example: "none"
